apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikibase
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/shared-secrets
      sourceRef:
        kind: GitRepository
        name: mardi-repo
        namespace: flux-system