apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: MYSQL_LOG_CONSOLE
          value: "{{ .Values.logConsole | default false }}"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MARIADB_REPLICATION_USER
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: MARIADB_REPLICATION_USER
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: MARIADB_REPLICATION_PASSWORD
        {{- if .Values.isPrimary }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: MYSQL_DATABASE
        {{- else }}
        - name: MARIADB_MASTER_HOST
          value: "{{ .Values.masterHost }}"
        {{- end }}
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
          items:
          {{- if .Values.isPrimary }}
          - key: shared.cnf
            path: shared.cnf
          - key: primary.cnf
            path: primary.cnf
          {{- else }}
          - key: shared.cnf
            path: shared.cnf
          - key: replica.cnf
            path: replica.cnf
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.mysql.storage.size }}